### ISSUE TITLE
base de datos que vamos a ocupar

### ISSUE THREAD

**Issue by Insmael** [DCC-CC4401/2018-1-Simmonds-Manzanilla-T3#1]
tenemos que eligir una base de datos a utilizar, no se que les tinca más a ustedes, seguir con sqlite3 o usar otra base de datos como postreql, a mi me tinca más la segunda, postgre. Igual podriamos preguntar en el foro.

**Comment by catapazv** [comment]
Igual me tinca usar postgresql

**Comment by hporro** [comment]
a mi igual me tinca :+1:

**Comment by benjujo** [comment]
A mí igual me daría miedo cambiarla así, no sé si puede romper algo :/
En todo caso, creo que daría lo mismo cual sea el administrador de bases de datos, ya que igual vamos a ocupar el ORM de django

**Comment by Insmael** [comment]
no se va a romper nada, si todavía no tenemos ni artículos ni usuarios.
yo también prefiero hacerlo con postgresql. Entonces, lo vamos a dejar como estaba, debido al trabajo extra que acarrea incorporar una nueva base de datos
